fix readme issues
RasaHQ/calm-langgraph-customer-service-comparison pull request #1
Opened 2024-08-06 10:45 UTC by dakshvar22

2024-08-06 14:21 UTC, amn41 approved these changes
thank you Daksh

2024-08-06 15:45 UTC, ArjaanBuijk requested changes
The link to the langgraph's bot does not work.

This is the correct one I believe:
https://langchain-ai.github.io/langgraph/tutorials/customer-support/customer-support/

2024-08-07 01:32 UTC, hugobowne commented
good catch @ArjaanBuijk ! fixed.

2024-08-07 06:52 UTC, dakshvar22 commented on README.md
> +There's a [YouTube video](https://www.youtube.com/watch?v=b3XsvoFWp4c) that provides a walkthrough of langgraph's implementation.
```suggestion
This is a reimplementation of langgraph's [customer support](https://langchain-ai.github.io/langgraph/tutorials/customer-support/customer-support/) example in Rasa's [CALM](https://rasa.com/docs/rasa-pro/calm/) paradigm 
There's a [YouTube video](https://www.youtube.com/watch?v=b3XsvoFWp4c) that provides a walkthrough of langgraph's implementation. 
```

2024-08-07 12:33 UTC, ArjaanBuijk approved these changes

2024-08-07 13:03 UTC, merged